---

version: "v-{build}"

image: Visual Studio 2022

clone_folder: C:\projects\deps.clj

environment:
  GRAALVM_HOME: C:\projects\deps.clj\graalvm\graalvm-jdk-21.0.1+12.1
  JAVA_HOME: C:\projects\deps.clj\graalvm\graalvm-jdk-21.0.1+12.1

cache:
  - C:\ProgramData\chocolatey\lib -> project.clj, appveyor.yml
  - '%USERPROFILE%\.m2 -> project.clj'
  - 'graalvm -> appveyor.yml'

build_script:
- cmd: >-
    powershell -Command "(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein.bat', 'lein.bat')"

    call lein self-install

- cmd: >-
    powershell -Command "if (Test-Path('bb.exe')) { return } else { (New-Object Net.WebClient).DownloadFile('https://github.com/babashka/babashka/releases/download/v0.9.162/babashka-0.9.162-windows-amd64.zip', 'bb.zip') }"

    powershell -Command "if (Test-Path('bb.exe')) { return } else { Expand-Archive bb.zip . }"

- cmd: >-
    call lein do clean, uberjar

    set /P DEPS_CLJ_VERSION=< resources\DEPS_CLJ_VERSION

    call java -jar "target/deps.clj-%DEPS_CLJ_VERSION%-standalone.jar" "-Sverbose" "-Spath"

- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    powershell -Command "if (Test-Path('graalvm')) { return } else { (New-Object Net.WebClient).DownloadFile('https://download.oracle.com/graalvm/21/archive/graalvm-jdk-21.0.1_windows-x64_bin.zip', 'graalvm.zip') }"

    powershell -Command "if (Test-Path('graalvm')) { return } else { Expand-Archive graalvm.zip graalvm }

    bb compile

    echo Creating zip archive

    set ARTIFACT=deps.clj-%DEPS_CLJ_VERSION%-windows-amd64.zip

    jar -cMf %ARTIFACT% deps.exe

    bb upload-artifact :file %ARTIFACT%

    dir

artifacts:
- path: deps.clj-*-windows-amd64.zip
  name: deps.exe

test_script:
- cmd: >-
    bb exe-test
